title: State of the Map Japan 2025
description: 世界を自由な地図にしよう
lang: ja
timezone: Asia/Tokyo
destination: "2025"

event:
  title: State of the Map Japan 2025
  date: 2025年12月6日
  dayofweek: 土曜日
  time: 11:00 - 18:00
  venue: 大阪大学中之島センター
  zip: 530-0005
  address: 大阪市北区中之島4-3-53
  map: https://osm.org/go/7QEzlyV6n?m=&way=231449174
  lat: 34.692725
  lon: 135.490429
  fee: 無料
  theme: Re:mapping
  message: OpenStreetMapは「自由な地図をみんなの手に」をスローガンに作成した地図データの集合体です。わたしたちは、この活動をさらに発展させるためにカンファレンスを企画しました。
  target: OpenStreetMap編集者、企業、技術者、研究者、行政関係者、シビックテックなどのコミュニティが集まり、各地・各領域の発表や交流を行います。
  host:
    - name: State of the Map Japan 2025 実行委員会
      url: https://stateofthemap.jp/2025/
    - name: 大阪大学SSI/いのち会議
      url: https://www.ssi.osaka-u.ac.jp/
  chairman: 
  cohost:
    - name: 一般社団法人 OpenStreetMap Foundation Japan
      url: https://www.osmf.jp/
  support:
    - name: 一般社団法人OSGeo日本支部(OSGeo.JP)
      url: https://www.osgeo.jp/
    - name: Open Source People Network
      url: https://ospn.jp/
    - name: 一般社団法人コード・フォー・ジャパン
      url: https://www.code4japan.org/
    - name: アカデミック・リソース・ガイド(arg)
      url: https://arg-corp.jp/
    - name: 一般社団法人地理情報システム学会
      url: https://www.gisa-japan.org/
  cooperation:
    - name: Code for OSAKA
      url: https://code4.osaka/

social:
  - title: State of the Map Japan
    icon: twitter
    url: https://x.com/SotM_Japan
  - title: OpenStreetMap Foundation Japan
    icon: twitter
    url: https://x.com/osmfj
  - title: OpenStreetMap Foundation Japan
    icon: facebook
    url: https://www.facebook.com/osmfj
  - title: youtube
    icon: youtube
    url: https://www.youtube.com/channel/UCKS6DjwrVC1gEx6PO0nX3TQ
  - title: github
    icon: github
    url: https://github.com/osmfj
  - title: wiki
    icon: pencil-square
    url: https://wiki.openstreetmap.org/wiki/JA:Main_Page
